# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deaddrop < Formula
  desc "Print your secrets without trusting your printer"
  homepage "https://github.com/jclement/deaddrop"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/deaddrop/releases/download/v0.1.1/deaddrop_darwin_amd64.tar.gz"
      sha256 "6af600a4b2efb10251b6bd805fc79e7795f34689fbaa6fc2aada17c8c9bbae33"

      define_method(:install) do
        bin.install "deaddrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/deaddrop/releases/download/v0.1.1/deaddrop_darwin_arm64.tar.gz"
      sha256 "628c9bb8525ebb9e0236c9c8713d24dbe078656f505f2da7f7bc771b5c30ca00"

      define_method(:install) do
        bin.install "deaddrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/deaddrop/releases/download/v0.1.1/deaddrop_linux_amd64.tar.gz"
      sha256 "fd69bdde206253643f8d1f73f222582547e0c686f05b0602ada45d2e8baa6c43"
      define_method(:install) do
        bin.install "deaddrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/deaddrop/releases/download/v0.1.1/deaddrop_linux_arm64.tar.gz"
      sha256 "b0899231de873c7e91443d19da754592f8ef535955f1972a3acfa922e1578dc6"
      define_method(:install) do
        bin.install "deaddrop"
      end
    end
  end
end
