# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doomsday < Formula
  desc "Backup for the end of the world"
  homepage "https://github.com/jclement/doomsday"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/doomsday/releases/download/v0.2.2/doomsday_0.2.2_darwin_amd64.tar.gz"
      sha256 "bce5c5b0597a5a5f7fecd965456388409e436d3dfc0b4e882480d9d6ccde9c6a"

      define_method(:install) do
        bin.install "doomsday"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/doomsday/releases/download/v0.2.2/doomsday_0.2.2_darwin_arm64.tar.gz"
      sha256 "041b24762168dc4942571f21c00be9453c4daf62110ba0b8aaeae1f66e275031"

      define_method(:install) do
        bin.install "doomsday"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/doomsday/releases/download/v0.2.2/doomsday_0.2.2_linux_amd64.tar.gz"
      sha256 "a4507df2ddb8a6f7555d8e64291d62de7a7e9d7308cf6a48687e741fdd6b5ced"
      define_method(:install) do
        bin.install "doomsday"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/doomsday/releases/download/v0.2.2/doomsday_0.2.2_linux_arm64.tar.gz"
      sha256 "2b0021f889dd630b3ffbfbf729b1133d68a8b26e8af7fa6f3db5f12c04d8ac62"
      define_method(:install) do
        bin.install "doomsday"
      end
    end
  end
end
