# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drillbit < Formula
  desc "A tool for managing SSH tunnels to PostgreSQL databases in Docker environments"
  homepage "https://github.com/jclement/drillbit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/drillbit/releases/download/v0.3.0/drillbit_0.3.0_darwin_amd64.tar.gz"
      sha256 "dc45b97bdc3882880ef1da28c572ec8d0cde1f6c74a88b8ea3e85169c10bc589"

      define_method(:install) do
        bin.install "drillbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/drillbit/releases/download/v0.3.0/drillbit_0.3.0_darwin_arm64.tar.gz"
      sha256 "6d2405331a131fb2317e3162c5b71f549d97d4410c76891a2fbb22fa4c347d73"

      define_method(:install) do
        bin.install "drillbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/drillbit/releases/download/v0.3.0/drillbit_0.3.0_linux_amd64.tar.gz"
      sha256 "7d4ef0126a11d909b34492cf18f73f6fc70a94540e9233aca59a79a3aae2f29e"
      define_method(:install) do
        bin.install "drillbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/drillbit/releases/download/v0.3.0/drillbit_0.3.0_linux_arm64.tar.gz"
      sha256 "069560cd2cf9320c0fe6ab56d40ced029e2005d0ffd615ee7414dd0c21f241db"
      define_method(:install) do
        bin.install "drillbit"
      end
    end
  end
end
