# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drillbit < Formula
  desc "A tool for managing SSH tunnels to PostgreSQL databases in Docker environments"
  homepage "https://github.com/jclement/drillbit"
  version "0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/drillbit/releases/download/v0.5/drillbit_0.5_darwin_amd64.tar.gz"
      sha256 "5622ff9627fd876f5e72862f160edff761682c7f4475eca9b01c993334e8abdf"

      define_method(:install) do
        bin.install "drillbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/drillbit/releases/download/v0.5/drillbit_0.5_darwin_arm64.tar.gz"
      sha256 "565ad7461add77874aff2e05c86747a0a7398e9e254b1e7c2ba1b878827f3643"

      define_method(:install) do
        bin.install "drillbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/drillbit/releases/download/v0.5/drillbit_0.5_linux_amd64.tar.gz"
      sha256 "ce99b766acd72662973f43dd5ae75b7be7210ad25a2333c62361e2cb33040986"
      define_method(:install) do
        bin.install "drillbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/drillbit/releases/download/v0.5/drillbit_0.5_linux_arm64.tar.gz"
      sha256 "94c70c5e9301699392f4fa9576dbaa9d6de4069f96937a562aea23f48a77a17b"
      define_method(:install) do
        bin.install "drillbit"
      end
    end
  end
end
