# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gatecrash < Formula
  desc "Gatecrash - expose local services through a remote server"
  homepage "https://github.com/jclement/gatecrash"
  version "0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/gatecrash/releases/download/v0.6/gatecrash_darwin_amd64.tar.gz"
      sha256 "cb8c80e59947466f0a429e7f9dd4617414a6a6373db7edbcb74311b972664beb"

      define_method(:install) do
        bin.install "gatecrash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/gatecrash/releases/download/v0.6/gatecrash_darwin_arm64.tar.gz"
      sha256 "37e7970fea58c90288c11ab31178408041db4dd544473c45b6a873ed00a71062"

      define_method(:install) do
        bin.install "gatecrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.6/gatecrash_linux_amd64.tar.gz"
      sha256 "c29341d2a66aa8f45b4144ffe91f3c3ce9983b1695402ea0de1a2882ce4b3353"
      define_method(:install) do
        bin.install "gatecrash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.6/gatecrash_linux_arm64.tar.gz"
      sha256 "4f616c88e36d2c2bd2ad134d59de9be7fa01201cb9a2ea65b5669ed4e01ead66"
      define_method(:install) do
        bin.install "gatecrash"
      end
    end
  end
end
