# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GatecrashServer < Formula
  desc "Gatecrash tunnel server with admin panel and automatic TLS"
  homepage "https://github.com/jclement/gatecrash"
  version "0.8.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.18/gatecrash-server_darwin_amd64.tar.gz"
      sha256 "60360bd9c1ee6dc7c9f4df79d88eca4fc0efa773fdc8cf814a90e7753459d756"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.18/gatecrash-server_darwin_arm64.tar.gz"
      sha256 "cc53cbb61d9523e3a00faed5bfb0df76af3e72e5180758f87c27723b0a11b059"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.18/gatecrash-server_linux_amd64.tar.gz"
      sha256 "5027ce1bdf0088a2a491131c5ff55e8bb2d01d1c15c88bf78274fd20ceb4ca12"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.18/gatecrash-server_linux_arm64.tar.gz"
      sha256 "638ff3ad28232aa52b416d99251fc6a03eca10c1755fe780416d23dad5b89d5e"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end
end
