# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gatecrash < Formula
  desc "Gatecrash tunnel client"
  homepage "https://github.com/jclement/gatecrash"
  version "0.8.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.10/gatecrash_darwin_amd64.tar.gz"
      sha256 "59386beb90938b3a05d09e5833963ffe92e8c720e0b010395140fd034a8aa511"

      define_method(:install) do
        bin.install "gatecrash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.10/gatecrash_darwin_arm64.tar.gz"
      sha256 "93fd3135a4173d39fb12e079a358889d122ece24eb26149ac9c67a0fc24e53b6"

      define_method(:install) do
        bin.install "gatecrash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.10/gatecrash_linux_amd64.tar.gz"
      sha256 "cf4fbcaa786c07809c73930510e5c7fcc743837cd253b9ebc3b791d5cb35049a"
      define_method(:install) do
        bin.install "gatecrash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.10/gatecrash_linux_arm64.tar.gz"
      sha256 "45d500cfac36cc124406417255c904cf12234ad276cb5f05baaec47c6f0ac7ba"
      define_method(:install) do
        bin.install "gatecrash"
      end
    end
  end
end
