# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GatecrashServer < Formula
  desc "Gatecrash tunnel server with admin panel and automatic TLS"
  homepage "https://github.com/jclement/gatecrash"
  version "0.8.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.6/gatecrash-server_darwin_amd64.tar.gz"
      sha256 "eeab013161e5e92ac56a14e32512ae8f3caafec4aece1795b5c8efeae6d5a709"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.6/gatecrash-server_darwin_arm64.tar.gz"
      sha256 "b441fe73c2b220f9227cb3862837eef7a1b329c8cfd3ba1d3167f6f25b192678"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.6/gatecrash-server_linux_amd64.tar.gz"
      sha256 "ba30051cbcccd91dc7077eb243ef01d270d8125e2bfd49ac70d581aa6dcaf0e4"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.8.6/gatecrash-server_linux_arm64.tar.gz"
      sha256 "2a561e003beeda50b98f97c69c0f886c0d9fdb0edf229b24b310a5010f32586e"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end
end
