# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Megaclawd < Formula
  desc "Sandboxed Claude Code development environments"
  homepage "https://github.com/jclement/megaclawd"
  version "0.1.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.0/megaclawd_darwin_amd64.tar.gz"
      sha256 "d4ec46a6721562523bc32e5753bd8bcba70896550881d15a0cc61bcb6c66f96a"

      define_method(:install) do
        bin.install "megaclawd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.0/megaclawd_darwin_arm64.tar.gz"
      sha256 "b6011d8b8142b7f2faff7487d63707092319bb21226550f438179076722df0e7"

      define_method(:install) do
        bin.install "megaclawd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.0/megaclawd_linux_amd64.tar.gz"
      sha256 "a69baa350f7566b1d984193e600af97ca2624c6459d9e166e4cbf08fced5bcff"
      define_method(:install) do
        bin.install "megaclawd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.0/megaclawd_linux_arm64.tar.gz"
      sha256 "9a6d9af21bfc4650dd6b2c03c2bc1504c17b9cdbbe4921de2683c37bf7a7f085"
      define_method(:install) do
        bin.install "megaclawd"
      end
    end
  end

  test do
    system bin/"megaclawd", "--version"
  end
end
