# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdfify < Formula
  desc "Convert Markdown to beautiful PDFs via Docker"
  homepage "https://github.com/jclement/pdfify"
  version "0.2.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/pdfify/releases/download/v0.2.1/pdfify_darwin_amd64.tar.gz"
      sha256 "cb85ae207fced9ffcdaf9df6f335daaee51edc1415a221e485fb27f74a863042"

      define_method(:install) do
        bin.install "pdfify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/pdfify/releases/download/v0.2.1/pdfify_darwin_arm64.tar.gz"
      sha256 "8805ff2704d1e5d1871babdec78b40562ea3aef46cd780f3fc0ae8476524c04c"

      define_method(:install) do
        bin.install "pdfify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/pdfify/releases/download/v0.2.1/pdfify_linux_amd64.tar.gz"
      sha256 "fce13fbc708cdeffc18389cf63799dcf88abd9c719f0bbad9354c5db276472a4"
      define_method(:install) do
        bin.install "pdfify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/pdfify/releases/download/v0.2.1/pdfify_linux_arm64.tar.gz"
      sha256 "86d650bdabed1b70d62b3756ecd055dcafb8ce2b6d33ddb157cb27266cf1be9c"
      define_method(:install) do
        bin.install "pdfify"
      end
    end
  end

  test do
    system bin/"pdfify", "--version"
  end
end
