# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pdfify < Formula
  desc "Convert Markdown to beautiful PDFs via Docker"
  homepage "https://github.com/jclement/pdfify"
  version "0.1.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/pdfify/releases/download/v0.1.0/pdfify_darwin_amd64.tar.gz"
      sha256 "f7e1f54293f08ca3731dc1e7c7d8fdbd0952dc0268aa9bf22c598ada1695db6d"

      define_method(:install) do
        bin.install "pdfify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/pdfify/releases/download/v0.1.0/pdfify_darwin_arm64.tar.gz"
      sha256 "7d95f30018243c553daf8fbc2845aa0de3b1757474a8b5bf7d8240b664c5f0c4"

      define_method(:install) do
        bin.install "pdfify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/pdfify/releases/download/v0.1.0/pdfify_linux_amd64.tar.gz"
      sha256 "516aded5a0200de4d4c57f33ca591cdb598e9f24362c9902b31e6ee1b3133918"
      define_method(:install) do
        bin.install "pdfify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/pdfify/releases/download/v0.1.0/pdfify_linux_arm64.tar.gz"
      sha256 "0e08ed99759721a87d271e22cd5a7f54fd1052b97faa48454942a8c4f86c3385"
      define_method(:install) do
        bin.install "pdfify"
      end
    end
  end

  test do
    system bin/"pdfify", "--version"
  end
end
