# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reviewbot < Formula
  desc "Agentic code review for the current branch"
  homepage "https://github.com/jclement/reviewbot"
  version "0.0.1"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/reviewbot/releases/download/v0.0.1/reviewbot_darwin_amd64.tar.gz"
      sha256 "f5d0ccf7d130624ed8b94e87e7faa17abc923d3568e67545c5a366cbc4bcb33a"

      define_method(:install) do
        bin.install "reviewbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/reviewbot/releases/download/v0.0.1/reviewbot_darwin_arm64.tar.gz"
      sha256 "a83937cfdfba04a5f8e9fee83f97c9ee85fd07ab08cf3274072f8a9229a74148"

      define_method(:install) do
        bin.install "reviewbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/reviewbot/releases/download/v0.0.1/reviewbot_linux_amd64.tar.gz"
      sha256 "f5c07d6c32d31dcb6785b94afa3a3cb48c7ff6263811965078984ecf9dcd7eb3"
      define_method(:install) do
        bin.install "reviewbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/reviewbot/releases/download/v0.0.1/reviewbot_linux_arm64.tar.gz"
      sha256 "577dfa431d4d9a418329b6ab4e5df0af93e268a40ef926a9378221bb814f0b15"
      define_method(:install) do
        bin.install "reviewbot"
      end
    end
  end

  test do
    system bin/"reviewbot", "--version"
  end
end
