# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellraiser < Formula
  desc "Sandboxed vibe-coding coordinator — one UI for many per-project worker containers"
  homepage "https://github.com/jclement/shellraiser"
  version "0.1.0"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/shellraiser/releases/download/v0.1.0/sr_darwin_amd64.tar.gz"
      sha256 "70e6f164428c4dea883cc20666313c3df44066e8747c216ca0a05f87b3fe2350"

      define_method(:install) do
        bin.install "sr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/shellraiser/releases/download/v0.1.0/sr_darwin_arm64.tar.gz"
      sha256 "f0e70767a8835425397ebfd0370defb678ea7999631741e020536d710a8bfb5f"

      define_method(:install) do
        bin.install "sr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/shellraiser/releases/download/v0.1.0/sr_linux_amd64.tar.gz"
      sha256 "30b4594bce7b793509c77cd7d1597c511c9ff1e56ffed08c85292103757382e1"
      define_method(:install) do
        bin.install "sr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/shellraiser/releases/download/v0.1.0/sr_linux_arm64.tar.gz"
      sha256 "ae363f41031f3ae87b32c951627fc1bffb7ff0f6c5abd37865d53ecd0ec217c6"
      define_method(:install) do
        bin.install "sr"
      end
    end
  end

  test do
    system "#{bin}/sr", "help"
  end
end
