# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitshot < Formula
  desc "Generate secure secrets and split them with Shamir secret sharing (SLIP-0039)"
  homepage "https://github.com/jclement/splitshot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.0/splitshot_darwin_amd64.tar.gz"
      sha256 "c96f5da8d2082ac15a7e0e23c593bc74a2dd50516fd20c343872e7d31a20f507"

      define_method(:install) do
        bin.install "splitshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.0/splitshot_darwin_arm64.tar.gz"
      sha256 "9513d6655c94353d4c59311f4e98709f2e8e168547d471dbd12b58b554118517"

      define_method(:install) do
        bin.install "splitshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.0/splitshot_linux_amd64.tar.gz"
      sha256 "1bbbb80bd2b80383f17665750b97605963c8ee66e16c94360455c60296463836"
      define_method(:install) do
        bin.install "splitshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.0/splitshot_linux_arm64.tar.gz"
      sha256 "483ecddac20a36fec93aeefcadc5ff23a70d8e7a4187d00f6a89a1d0b43b2bbb"
      define_method(:install) do
        bin.install "splitshot"
      end
    end
  end

  test do
    system "#{bin}/splitshot", "version"
  end
end
