# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenwatch < Formula
  desc "Sync your Claude Code & Codex token stats to TokenWatch"
  homepage "https://tokens.onewheelgeek.net"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.1.6/tokenwatch_darwin_amd64.tar.gz"
      sha256 "670efcb9c1bc0e1b3fd6863821b0c376abf1b90c1f713a1f1e83d6bef96424e8"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.1.6/tokenwatch_darwin_arm64.tar.gz"
      sha256 "6bf900384edcd986a9d04ea0d61f98611383173f338ede564723fdda3d381127"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.1.6/tokenwatch_linux_amd64.tar.gz"
      sha256 "275a39502627a7fa004730df64e77a0e8af341c2aa29548c564b6585938740a5"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.1.6/tokenwatch_linux_arm64.tar.gz"
      sha256 "7ccda0d976a1b0f526133cb2a18423ef465d4f86cedb6417f9b745e30dbdabf7"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  def caveats
    <<~EOS
      Pair this device with a code from https://tokens.onewheelgeek.net (Settings):
        tokenwatch --pair <CODE>
      Then sync once with `tokenwatch` or continuously with `tokenwatch --continuous`.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenwatch --version")
  end
end
