# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenwatch < Formula
  desc "Sync your Claude Code & Codex token stats to TokenWatch"
  homepage "https://tokens.onewheelgeek.net"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.0/tokenwatch_darwin_amd64.tar.gz"
      sha256 "98812ce02ca0f4fa5dd2bd20624fe808d03cb0c3a96f593384cf320680a10ddf"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.0/tokenwatch_darwin_arm64.tar.gz"
      sha256 "acf4ed2a388da812df72cb8f433d2a31e32d7a34eb49a0d83456aec748adbe20"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.0/tokenwatch_linux_amd64.tar.gz"
      sha256 "c41396347e9ed688b2d681b9d3725706b1b60f171aaa070c3fab2a88ea269bd3"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.0/tokenwatch_linux_arm64.tar.gz"
      sha256 "ea9e84086d8a0bdf823e1399ff5367530feec6695b35fd9c14bb53b0d76735a5"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  def caveats
    <<~EOS
      Pair this device with a code from https://tokens.onewheelgeek.net (Settings):
        tokenwatch --pair <CODE>
      Then sync once with `tokenwatch` or continuously with `tokenwatch --continuous`.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenwatch --version")
  end
end
