# This file was generated by GoReleaser. DO NOT EDIT.
cask "autotun" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "23d5c37a036a15811af328520a8e3e16596ba51f1ca6058184ad3a51d0d3a5e3"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8289989d1458ea301033b3457da718b1019451c65d92fc4bcc5d637afcc2bfeb"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb340e5c5c3bf479e61cda619040c24fb4773be4616969e1db7aeaea44e48a1e"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6a34c381dae17bc00d57cd090719ffb336f3c1a912ba1c5b28433c61780e2b6"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "autotun"
  desc "Forward every port your remote dev box opens, automatically"
  homepage "https://github.com/jclement/autotun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autotun"

  postflight do
    if OS.mac?
      # Strip the quarantine flag so a downloaded binary runs without a
      # Gatekeeper prompt.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/autotun"],
                     must_succeed: false
    end
  end

  # No zap stanza required

end
