# This file was generated by GoReleaser. DO NOT EDIT.
cask "autotun" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "d062f8585b97b43d7062a5c8a9b7c59f0d35718898dbd0a6563faecfaed84708"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5c8880b18960c638a0b98b861e8fa4ba1b030fecc8e27e784a102d8c9de5a59"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "451dd1cc9ad392ae17bd9b7e05d08664f14ee6ec268f97a0d9a4826b9938b634"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4db31a813aa22f229305187664b19a98e68eefc643c446871b3b81616235f307"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "autotun"
  desc "Forward every port your remote dev box opens, automatically"
  homepage "https://github.com/jclement/autotun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autotun"

  postflight do
    if OS.mac?
      # Strip the quarantine flag so a downloaded binary runs without a
      # Gatekeeper prompt.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/autotun"],
                     must_succeed: false
    end
  end

  # No zap stanza required

end
