# This file was generated by GoReleaser. DO NOT EDIT.
cask "autotun" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d63886dc695f0537f22dad1cf8d66812131670f3c042d4dff95588b63e3e0174"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dcae31226caf83e1304beae26752b96449f5e334ac38cfeab94704cc7c18ef09"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f49186b6df3202ad6b3d2e82bde264a3d2b17fc18ef4df5e7afd2aec5a51f86a"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "43f4dd94dacd356d4e12a3c8b7644d8070e58aaccfe72f7b9b55cf0c227fd887"
      url "https://github.com/jclement/autotun/releases/download/v#{version}/autotun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "autotun"
  desc "Forward every port your remote dev box opens, automatically"
  homepage "https://github.com/jclement/autotun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autotun"

  postflight do
    if OS.mac?
      # Strip the quarantine flag so a downloaded binary runs without a
      # Gatekeeper prompt.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/autotun"],
                     must_succeed: false
    end
  end

  # No zap stanza required

end
