# This file was generated by GoReleaser. DO NOT EDIT.
cask "clamtotal" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "0aeae5b856d1a15b2b621a21e2eee91279dbc4eea4c76d82657d94d2699f1a2d"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d7a155731c6bc8db2b248eefb184dd6cfc581dc987486f503b1325da01af418"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e717ba4273f58b5122cd2c8f6b0caeed9e201b2cdf24415dc430e24d942ba6f"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fdbe29c7cd36f0054baedc58b290c264516aa3f4e910a5aa8d2e2c4265de788e"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clamtotal"
  desc "Remote ClamAV scanning client — hash-first, cache-friendly folder scans"
  homepage "https://github.com/jclement/clamtotal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clamtotal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clamtotal"]
    end
  end

  # No zap stanza required

end
