# This file was generated by GoReleaser. DO NOT EDIT.
cask "clamtotal" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d57b61d56a881fd8821501dd3790ac93dec59701e27e2b12ec2dbce52c05b226"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8363bb68e3e7674fcf19dc89f6b15b2fe64a697e59b62cd888d04dba943325d7"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7ad76ca8b93235370408032602a7f15d109e8a2534616035711f5f1e796004f"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6223e17c828d5c630b388979c5ad4a2a2d7f2deeb6e93d8eec36aaffa748652"
      url "https://github.com/jclement/clamtotal/releases/download/v#{version}/clamtotal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clamtotal"
  desc "Remote ClamAV scanning client — hash-first, cache-friendly folder scans"
  homepage "https://github.com/jclement/clamtotal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clamtotal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clamtotal"]
    end
  end

  # No zap stanza required

end
