# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtun" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "8ff200f36712726d1aaf0bf367305303f8e78d336b85e4ed51884e51b354cd00"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "71d935648b2906a876e3993fe68832776f09fe185c6f387f1fcbd5229085781f"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e187e9691e21248f7dedf66a8b62a8367be09e6d5f32067cc8b13be68492e720"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aae748fa3679c9f3af5cc34d42d665e7c70bbc0ab20110cfd3d50a5291caced2"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devtun"
  desc "Your remote dev box, but it behaves like localhost — ports, secrets, SSH agent and browser over one SSH connection"
  homepage "https://github.com/jclement/devtun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtun"

  postflight do
    if OS.mac?
      # Strip the quarantine flag so a downloaded binary runs without a
      # Gatekeeper prompt.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/devtun"],
                     must_succeed: false
    end
  end

  # No zap stanza required
end
