# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtun" do
  version "0.1.23"

  on_macos do
    on_arm do
      sha256 "3eb4bf585ef7b1d763b86f92f92324a32ab5b26b2ce9de05e5bbaa853047b8da"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "41f90a7ac6427359f7afe2f5ba8db978a2159d6da43643e4dd6484f28225407f"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55c4919889d0175ca1919e910e116597c5f2119f9af73b98c595d1f40ce2b842"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fb6cc066e57f72d390a215149f93825bb6f92f9a703a641b568ce6e8f3bc7fa"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devtun"
  desc "Your remote dev box, but it behaves like localhost — ports, secrets, SSH agent and browser over one SSH connection"
  homepage "https://github.com/jclement/devtun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtun"

  postflight do
    if OS.mac?
      # Strip the quarantine flag so a downloaded binary runs without a
      # Gatekeeper prompt.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/devtun"],
                     must_succeed: false
    end
  end

  # No zap stanza required
end
