# This file was generated by GoReleaser. DO NOT EDIT.
cask "devtun" do
  version "0.1.21"

  on_macos do
    on_arm do
      sha256 "275830b7f7dce31c530121ae3927aa13b09ae5fd317f9c644e16a064f710ea63"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0443894bd37d58f519a6ebcd56bb26c4d2d5193d40e391c2751113b5ada6b7ac"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "41a9b28f74a0b91b586264f685ac1ae43892950af44920f0f8264f1339d8c1f2"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75f2ca5af5b27eaaf06a8714a34e1d2af6ea696deec1fbe2a2a658b15f6e611f"
      url "https://github.com/jclement/devtun/releases/download/v#{version}/devtun_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devtun"
  desc "Your remote dev box, but it behaves like localhost — ports, secrets, SSH agent and browser over one SSH connection"
  homepage "https://github.com/jclement/devtun"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devtun"

  postflight do
    if OS.mac?
      # Strip the quarantine flag so a downloaded binary runs without a
      # Gatekeeper prompt.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/devtun"],
                     must_succeed: false
    end
  end

  # No zap stanza required
end
