# This file was generated by GoReleaser. DO NOT EDIT.
cask "opproxy" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "22881d0544b5545e0e42825f0381ec064f485745738a3d0289b2ada0a7ba802e"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "de41dd5c488adee8a9859c0057f2c1618707e475b630e5b4f88a33578f488b5e"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ec4106e51f0762db26c09df0959da02ed0a6602a4973ad2b6b9850b8a8752444"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1747f5dce193fd84735845905f2f6f2de25e98dbe789e64f77be62d9e9cb4d4b"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opproxy"
  desc "Use your workstation's 1Password vault from a remote dev box, over SSH"
  homepage "https://github.com/jclement/opproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opproxy"
  bash_completion "completions/opproxy.bash"
  fish_completion "completions/opproxy.fish"
  zsh_completion "completions/opproxy.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opproxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run the proxy on the machine with your unlocked vault:
      opproxy install <host>     # puts the shim on the remote box as `op`
      opproxy proxy   <host>     # serves secrets, asking you to approve each one
  EOS
end
