# This file was generated by GoReleaser. DO NOT EDIT.
cask "opproxy" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "0979e2622ed56b4744d898daa9ca9083365abf20898a279a919822317bc8bac4"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jclement/opproxy"
    end
    on_intel do
      sha256 "32eea18becbc00b25826795eecfa63a02d512e5c0c04cfedcf643c1627572b25"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jclement/opproxy"
    end
  end
  on_linux do
    on_arm do
      sha256 "69891bbaef89588a4692949db2b82da38e1313d1a283f12ec5ad17871f0463a3"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jclement/opproxy"
    end
    on_intel do
      sha256 "cd79da7339f5b9cec08921bc708427fcea333079ded268a0c592dc66b9b0593b"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jclement/opproxy"
    end
  end

  name "opproxy"
  desc "Use your workstation's 1Password vault from a remote dev box, over SSH"
  homepage "https://github.com/jclement/opproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opproxy"
  bash_completion "completions/opproxy.bash"
  fish_completion "completions/opproxy.fish"
  zsh_completion "completions/opproxy.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opproxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run the proxy on the machine with your unlocked vault:
      opproxy install <host>     # puts the shim on the remote box as `op`
      opproxy proxy   <host>     # serves secrets, asking you to approve each one
  EOS
end
