# This file was generated by GoReleaser. DO NOT EDIT.
cask "opproxy" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "17a449d8eaf6bb73b13725ca2dcdd83fb088b3624397da7fe1277f19e1f67af6"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "17285674a52a4aa675bf15421fcb4d5a0ece695ffa74a379d2b93e665800d642"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a0deb5a8f21bf777f636b6915eaf08c2c4006acc74fa86aee277c9a7f69c2f4f"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "94ac61a67a5297e58199bc5ce04faad2fad810ea76be9b7d1d13bfd13f4117f2"
      url "https://github.com/jclement/opproxy/releases/download/v#{version}/opproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opproxy"
  desc "Use your workstation's 1Password vault from a remote dev box, over SSH"
  homepage "https://github.com/jclement/opproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opproxy"
  bash_completion "completions/opproxy.bash"
  fish_completion "completions/opproxy.fish"
  zsh_completion "completions/opproxy.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opproxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run the proxy on the machine with your unlocked vault:
      opproxy install <host>     # puts the shim on the remote box as `op`
      opproxy proxy   <host>     # serves secrets, asking you to approve each one
  EOS
end
