# This file was generated by GoReleaser. DO NOT EDIT.
cask "quire" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a20d9b8fb82817aa4d3eedb04f904ddb1fe80c0236e05d3e6ea4c27d1ea87dd4"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "acfa05a918527d71abebb38fb92b3c4b87ef9db7f38936d82a718cd31117c4fb"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c52a15b2aad3a1a1f46ec872ec32537b26ec865554a3d88b8e004e25c29c6b7b"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a09052bb57f311c83f6a20cbd126371705f92b6b7970f272ac6587893d29e09"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_linux_amd64.tar.gz"
    end
  end

  name "quire"
  desc "Self-hosted personal knowledge and work hub — markdown on disk, agent-operable over MCP"
  homepage "https://github.com/jclement/quire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quire"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/quire"]
    end
  end

  # No zap stanza required
end
