# This file was generated by GoReleaser. DO NOT EDIT.
cask "quire" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "820bd137d41f2b556ef644a336f218dbdfe8127191bccf6a20aa153e51a9565a"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1359f47e57a7419940013806e0afce52db24d8926ee5198eae5715f1daa82b73"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "458b96867d2b0aa07d255e4356b42d54b85e951d7b4945d2b7b6023ab37b522e"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "15609faaf01c3313ebae6d6602334c77c861943ed2b805b9bef68a5419984923"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_linux_amd64.tar.gz"
    end
  end

  name "quire"
  desc "Self-hosted personal knowledge and work hub — markdown on disk, agent-operable over MCP"
  homepage "https://github.com/jclement/quire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quire"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/quire"]
    end
  end

  # No zap stanza required
end
