# This file was generated by GoReleaser. DO NOT EDIT.
cask "quire" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "3a711ffa77223b79f48e9b9a105caaff7f071ce0347b2516f4133a49e2f4415a"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2968dbdca320fd9c5b1d65bdd17fdfe400ad024d66da3c563a3b9223be455279"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1863d560d2eeef9d58f43eaf4c9799f1135213fccf78fb07372ec9d4a6a5e427"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "78468ea05df0a8069fdc257c78c87dc7accac61bae620b99dd5e52adc72550de"
      url "https://github.com/jclement/quire/releases/download/v#{version}/quire_#{version}_linux_amd64.tar.gz"
    end
  end

  name "quire"
  desc "Self-hosted personal knowledge and work hub — markdown on disk, agent-operable over MCP"
  homepage "https://github.com/jclement/quire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quire"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/quire"]
    end
  end

  # No zap stanza required
end
