# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cone < Formula
  desc "A coordination board for coding agents — a folder is the protocol"
  homepage "https://github.com/jclement/cone"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/cone/releases/download/v0.4.0/cone_0.4.0_darwin_amd64.tar.gz"
      sha256 "97c2d3de951977f4d84ecbf42d262993fbf09cc847f65c3d7b3029241f1fdd60"

      define_method(:install) do
        bin.install "cone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/cone/releases/download/v0.4.0/cone_0.4.0_darwin_arm64.tar.gz"
      sha256 "02d92d1d016d92f4947677336d069fc68113237d7d4e2b4f0cf72758bf9085db"

      define_method(:install) do
        bin.install "cone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/cone/releases/download/v0.4.0/cone_0.4.0_linux_amd64.tar.gz"
      sha256 "590b4923b921286a1dcae9546c666278efb3a4187e71a83d7a71d5c2f8adfe0d"
      define_method(:install) do
        bin.install "cone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/cone/releases/download/v0.4.0/cone_0.4.0_linux_arm64.tar.gz"
      sha256 "552e1b461f04846bb9f2128722fab03be361853f6990f7fc4c2475017e6a93f6"
      define_method(:install) do
        bin.install "cone"
      end
    end
  end

  test do
    system "#{bin}/cone", "version"
  end
end
