# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cone < Formula
  desc "A coordination board for coding agents — a folder is the protocol"
  homepage "https://github.com/jclement/cone"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/cone/releases/download/v0.2.0/cone_0.2.0_darwin_amd64.tar.gz"
      sha256 "63383fae7e696363ca55f12e5df8cbcd9a07e449d272781bd79cfacc92c21433"

      define_method(:install) do
        bin.install "cone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/cone/releases/download/v0.2.0/cone_0.2.0_darwin_arm64.tar.gz"
      sha256 "4ab4fa082ca3f95f748ddd38a46936882f847809b03247e3405338b9e139434e"

      define_method(:install) do
        bin.install "cone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/cone/releases/download/v0.2.0/cone_0.2.0_linux_amd64.tar.gz"
      sha256 "ab333b4ec4e5d1e5ea15d85a5a284082d82152fbbf596a409ec6961937d365c8"
      define_method(:install) do
        bin.install "cone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/cone/releases/download/v0.2.0/cone_0.2.0_linux_arm64.tar.gz"
      sha256 "e4129465c823173ab82040c5005ff75c280f6fb2f70f5070c3758284e9f55392"
      define_method(:install) do
        bin.install "cone"
      end
    end
  end

  test do
    system "#{bin}/cone", "version"
  end
end
