# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdu < Formula
  desc "Fancy disk usage — a colorful TUI for finding what's eating your disk"
  homepage "https://github.com/jclement/fdu"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/fdu/releases/download/v0.1.1/fdu_0.1.1_darwin_amd64.tar.gz"
      sha256 "6a828ec5e73663e4f9a1326f9fa55bfdb387156d956fa96f0fe91152637dae6f"

      define_method(:install) do
        bin.install "fdu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/fdu/releases/download/v0.1.1/fdu_0.1.1_darwin_arm64.tar.gz"
      sha256 "1b54e48cdec0c9b3320b3a53cd668fb056feaf04ea6129ec6cff78057fe850d6"

      define_method(:install) do
        bin.install "fdu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/fdu/releases/download/v0.1.1/fdu_0.1.1_linux_amd64.tar.gz"
      sha256 "b922236b4b0d904c89706f2c8262ed90c8889c4647ed12947d4944a6d080f96f"
      define_method(:install) do
        bin.install "fdu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/fdu/releases/download/v0.1.1/fdu_0.1.1_linux_arm64.tar.gz"
      sha256 "bce16367b1c47bb5676c4e50a540eca908dbc0f4d3252638e410d7e2e1157ff0"
      define_method(:install) do
        bin.install "fdu"
      end
    end
  end

  test do
    system "#{bin}/fdu", "--version"
  end
end
