# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fdu < Formula
  desc "Fancy disk usage — a colorful TUI for finding what's eating your disk"
  homepage "https://github.com/jclement/fdu"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/fdu/releases/download/v0.1.0/fdu_0.1.0_darwin_amd64.tar.gz"
      sha256 "ffabcd70aec1fb85fe53438451af05901e46bb8c8f6f0f9c3ff6efe1527f5f34"

      define_method(:install) do
        bin.install "fdu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/fdu/releases/download/v0.1.0/fdu_0.1.0_darwin_arm64.tar.gz"
      sha256 "ef0f4d2a0cb2ab2c7a2146717a56ee2aad25cf8ec613c734a499277f16366fbd"

      define_method(:install) do
        bin.install "fdu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/fdu/releases/download/v0.1.0/fdu_0.1.0_linux_amd64.tar.gz"
      sha256 "457e560f871d219dd07973a1818f9ff0e85d1e2e5556e652c0d13878880d7f78"
      define_method(:install) do
        bin.install "fdu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/fdu/releases/download/v0.1.0/fdu_0.1.0_linux_arm64.tar.gz"
      sha256 "7bc24ef65e09326e807328a7b7721d75b42f6401c9d1f322b6c9ce5cdf3d2482"
      define_method(:install) do
        bin.install "fdu"
      end
    end
  end

  test do
    system "#{bin}/fdu", "--version"
  end
end
