# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GatecrashServer < Formula
  desc "Gatecrash tunnel server with admin panel and automatic TLS"
  homepage "https://github.com/jclement/gatecrash"
  version "0.9.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/gatecrash/releases/download/v0.9.5/gatecrash-server_darwin_amd64.tar.gz"
      sha256 "1866a15cb637ba53266b11c37e5adb048d830df8035b1b4e51793094ab4c90b6"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/gatecrash/releases/download/v0.9.5/gatecrash-server_darwin_arm64.tar.gz"
      sha256 "e10c0265623db5a6635ae18ec44fa0109f29944ab3da1570ab7efd744c5e47d7"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.9.5/gatecrash-server_linux_amd64.tar.gz"
      sha256 "ff2bdae835fcff4e5976f581cfb687f8b85c8bf83ed12b1a8ba4fd15eacf85a1"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.9.5/gatecrash-server_linux_arm64.tar.gz"
      sha256 "c39223e343b72e0d517ee4d11d29db9221ac9a306238a4cf3456c62ee5340426"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end
end
