# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GatecrashServer < Formula
  desc "Gatecrash tunnel server with admin panel and automatic TLS"
  homepage "https://github.com/jclement/gatecrash"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/gatecrash/releases/download/v0.10.0/gatecrash-server_darwin_amd64.tar.gz"
      sha256 "9c022faf7c1a29c6f29248ff3302df4b13d2c8e11a589e0918bf79c6bdf2aac6"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/gatecrash/releases/download/v0.10.0/gatecrash-server_darwin_arm64.tar.gz"
      sha256 "da4effd2490b0447209fbd5d9d0bce53e0ecc5903a609823eb67ed321412d7dc"

      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.10.0/gatecrash-server_linux_amd64.tar.gz"
      sha256 "d3d69915bc78d08964b237a15e553a7c1f966acbc389ff64d8888a1cc1386e10"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/gatecrash/releases/download/v0.10.0/gatecrash-server_linux_arm64.tar.gz"
      sha256 "e4c7889237e8caf1cce40ca96b64277db1a56f8542a17a329b419162f343fa0e"
      define_method(:install) do
        bin.install "gatecrash-server"
      end
    end
  end
end
