# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Megaclawd < Formula
  desc "Sandboxed Claude Code development environments"
  homepage "https://github.com/jclement/megaclawd"
  version "0.1.2"
  license "MIT"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.2/megaclawd_darwin_amd64.tar.gz"
      sha256 "929d55d28290aa0d27aff81dc84aefbd4ee4f549994905c59e982cdb1505bebd"

      define_method(:install) do
        bin.install "megaclawd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.2/megaclawd_darwin_arm64.tar.gz"
      sha256 "91aca7a464ee4d42ec198c7bf41b374c8f1b04d3644989b4fc0a233fbded00f0"

      define_method(:install) do
        bin.install "megaclawd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.2/megaclawd_linux_amd64.tar.gz"
      sha256 "2cc82ed4e9a3a04ac13d998d19e574f78e743082da732633d3b3d907e3916cc7"
      define_method(:install) do
        bin.install "megaclawd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/megaclawd/releases/download/v0.1.2/megaclawd_linux_arm64.tar.gz"
      sha256 "bde1b5b133f62b877932e8af3f61d383e8a9d050a78468f0b09e9d798bdc0fdc"
      define_method(:install) do
        bin.install "megaclawd"
      end
    end
  end

  test do
    system bin/"megaclawd", "--version"
  end
end
