# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanos3 < Formula
  desc "Tiny S3-compatible object store with a live web dashboard"
  homepage "https://github.com/jclement/nanos3"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/nanos3/releases/download/v0.1.3/nanos3_0.1.3_darwin_amd64.tar.gz"
      sha256 "194780a8092d3bf30b5f6327224d821b2271bd5e73f9d687bd569e666f7832ee"

      define_method(:install) do
        bin.install "nanos3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/nanos3/releases/download/v0.1.3/nanos3_0.1.3_darwin_arm64.tar.gz"
      sha256 "70def52708287d0e2956815d28c719d2033dff0cbecf402bfd2c9d48d5bb782f"

      define_method(:install) do
        bin.install "nanos3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/nanos3/releases/download/v0.1.3/nanos3_0.1.3_linux_amd64.tar.gz"
      sha256 "0b0cf240ab7a39f8b3a0ca452cc0d3e35831bdc606195d8cc5412847fbb3f5a8"
      define_method(:install) do
        bin.install "nanos3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/nanos3/releases/download/v0.1.3/nanos3_0.1.3_linux_arm64.tar.gz"
      sha256 "5d64f3e4c23400571762ab276cf6d59ea72ed6ce5e1acf081da7cb59000b0eb7"
      define_method(:install) do
        bin.install "nanos3"
      end
    end
  end

  test do
    system "#{bin}/nanos3", "--version"
  end
end
