# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanos3 < Formula
  desc "Tiny S3-compatible object store with a live web dashboard"
  homepage "https://github.com/jclement/nanos3"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.0/nanos3_0.2.0_darwin_amd64.tar.gz"
      sha256 "785824565d8fb780f4f3a94c38a5804325713b2b928fb0b0ee5246ead9fa1523"

      define_method(:install) do
        bin.install "nanos3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.0/nanos3_0.2.0_darwin_arm64.tar.gz"
      sha256 "b079409a4d19150d827242c53d7d90905abf5db98334139a1b19ed69306721d8"

      define_method(:install) do
        bin.install "nanos3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.0/nanos3_0.2.0_linux_amd64.tar.gz"
      sha256 "660921e12fb1592df27d4b39b0966d0b79e157c088dc04f606a8f93fd2d73475"
      define_method(:install) do
        bin.install "nanos3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.0/nanos3_0.2.0_linux_arm64.tar.gz"
      sha256 "ce3471f7fdd3d5b4f4e9e9e7c9f388340c98ab92f0a1f679fc42d05e90837877"
      define_method(:install) do
        bin.install "nanos3"
      end
    end
  end

  test do
    system "#{bin}/nanos3", "--version"
  end
end
