# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanos3 < Formula
  desc "Tiny S3-compatible object store with a live web dashboard"
  homepage "https://github.com/jclement/nanos3"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.1/nanos3_0.2.1_darwin_amd64.tar.gz"
      sha256 "5c8875d5f17b4cf6bb9fad1cc37fcdaf47ca7d953ed9e202f1943e53a0c16131"

      define_method(:install) do
        bin.install "nanos3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.1/nanos3_0.2.1_darwin_arm64.tar.gz"
      sha256 "5f5e8a686cd5adceb634c394e575261f3ae9eff9c8a4504af596e4e8fca21b86"

      define_method(:install) do
        bin.install "nanos3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.1/nanos3_0.2.1_linux_amd64.tar.gz"
      sha256 "0f2a57e191e7f295c939436d698ade6dd8cdf76bc6366aaace5418fe9a2b856e"
      define_method(:install) do
        bin.install "nanos3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/nanos3/releases/download/v0.2.1/nanos3_0.2.1_linux_arm64.tar.gz"
      sha256 "dc96713e93532caed18c9e3c28ddf95dbd0689f69b016eb7ae7f6cf5009fa7ed"
      define_method(:install) do
        bin.install "nanos3"
      end
    end
  end

  test do
    system "#{bin}/nanos3", "--version"
  end
end
