# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Picos3 < Formula
  desc "Tiny single-bucket S3-compatible object store"
  homepage "https://github.com/jclement/picos3"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/picos3/releases/download/v0.2.0/picos3_0.2.0_darwin_amd64.tar.gz"
      sha256 "c3f74305173b040ff047b6311aa0cd297b6cc89ef9acc6b70951413353467893"

      define_method(:install) do
        bin.install "picos3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/picos3/releases/download/v0.2.0/picos3_0.2.0_darwin_arm64.tar.gz"
      sha256 "13662f555000e3930dcba64a372e49177b2acb0ac4e89b4aecf1d9cccda2c73c"

      define_method(:install) do
        bin.install "picos3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/picos3/releases/download/v0.2.0/picos3_0.2.0_linux_amd64.tar.gz"
      sha256 "1c49ee3cfc9cc9c2f56800c54987452bdefbd3dbaee6f022aed92e1ccb2e1690"
      define_method(:install) do
        bin.install "picos3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/picos3/releases/download/v0.2.0/picos3_0.2.0_linux_arm64.tar.gz"
      sha256 "033a22f047ebdb8aee3cbb6fb249a947c6a4a9f9224070999f9f70048a614de1"
      define_method(:install) do
        bin.install "picos3"
      end
    end
  end

  test do
    system "#{bin}/picos3", "-version"
  end
end
