# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Picos3 < Formula
  desc "Tiny single-bucket S3-compatible object store"
  homepage "https://github.com/jclement/picos3"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/picos3/releases/download/v0.1.0/picos3_0.1.0_darwin_amd64.tar.gz"
      sha256 "aaccc500758a2d99e5de74a0937444cddbe32ef312111afd10d67fd1665ca01f"

      define_method(:install) do
        bin.install "picos3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/picos3/releases/download/v0.1.0/picos3_0.1.0_darwin_arm64.tar.gz"
      sha256 "c6dc87077bb3dc1b34061e0f178dab64666f370719572c24013c501adf3d8710"

      define_method(:install) do
        bin.install "picos3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/picos3/releases/download/v0.1.0/picos3_0.1.0_linux_amd64.tar.gz"
      sha256 "a2a154109f661e8d23e5159456180f634096115f9bdc2d0f92a9abfcd9351bdf"
      define_method(:install) do
        bin.install "picos3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/picos3/releases/download/v0.1.0/picos3_0.1.0_linux_arm64.tar.gz"
      sha256 "6a09a76632ade8723f7b9a06a221256e3f633460d8c1a2cd2efaf2d481e47778"
      define_method(:install) do
        bin.install "picos3"
      end
    end
  end

  test do
    system "#{bin}/picos3", "-version"
  end
end
