# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitshot < Formula
  desc "Generate secure secrets and split them with Shamir secret sharing (SLIP-0039)"
  homepage "https://github.com/jclement/splitshot"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.1/splitshot_darwin_amd64.tar.gz"
      sha256 "0c360c3262ff05a0bc11af6f3fc6229a55ffbf11b7cae42a203c026f4840a9cf"

      define_method(:install) do
        bin.install "splitshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.1/splitshot_darwin_arm64.tar.gz"
      sha256 "ee66af77dcfdd9f0a4d97d84d23667142bb318a65ba77408fdcd64b48f99431c"

      define_method(:install) do
        bin.install "splitshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.1/splitshot_linux_amd64.tar.gz"
      sha256 "e8c1f7107c4dc23bedb71b85585bdd3515ff09fc646f4c802936e5d284c322b1"
      define_method(:install) do
        bin.install "splitshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/splitshot/releases/download/v0.1.1/splitshot_linux_arm64.tar.gz"
      sha256 "6e499f3b16a50d738829abc95cd6c3150285f347a8da30ca59d2a67224f02c26"
      define_method(:install) do
        bin.install "splitshot"
      end
    end
  end

  test do
    system "#{bin}/splitshot", "version"
  end
end
