# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenwatch < Formula
  desc "Sync your Claude Code & Codex token stats to TokenWatch"
  homepage "https://tokens.onewheelgeek.net"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.0/tokenwatch_darwin_amd64.tar.gz"
      sha256 "5dd360fd17732d2a3f1843f7ca808f4fc6c64ad066dc7f8648b84dc20b8634c5"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.0/tokenwatch_darwin_arm64.tar.gz"
      sha256 "beb3aca8d2f58e50f256450fb6f709e65dbe184dd6bdd1c4131e80dc848b77d9"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.0/tokenwatch_linux_amd64.tar.gz"
      sha256 "7b2ae4ba650cf7e73353e81ea2d07273e33ad24132098891c0603053b155a73e"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.0/tokenwatch_linux_arm64.tar.gz"
      sha256 "e2f512097de8aa74d95b284a5dee3da8b74a7a90815ac0d6741b4966ef4849c5"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  def caveats
    <<~EOS
      Pair this device with a code from https://tokens.onewheelgeek.net (Settings):
        tokenwatch --pair <CODE>
      Then sync once with `tokenwatch` or continuously with `tokenwatch --continuous`.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenwatch --version")
  end
end
