# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenwatch < Formula
  desc "Sync your Claude Code & Codex token stats to TokenWatch"
  homepage "https://tokens.onewheelgeek.net"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.2/tokenwatch_darwin_amd64.tar.gz"
      sha256 "17dda069f1344ab6a57c3da42958aa9d914dd40cf586b862c48eadcef26b460f"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.2/tokenwatch_darwin_arm64.tar.gz"
      sha256 "880b1b99c5abbb4039312465cc0a12d546fc61763e0e88540fc7bd96ef0eb027"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.2/tokenwatch_linux_amd64.tar.gz"
      sha256 "9cbcae21b41a3d63581af69724678536a87dd1f1cdcabbe50249306002bafe79"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.2.2/tokenwatch_linux_arm64.tar.gz"
      sha256 "dbdb69e2ea89827f1228ad15ed7fdeb607afaac0e182bd3ee141fb9c361d4ea8"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  def caveats
    <<~EOS
      Pair this device with a code from https://tokens.onewheelgeek.net (Settings):
        tokenwatch --pair <CODE>
      Then sync once with `tokenwatch` or continuously with `tokenwatch --continuous`.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenwatch --version")
  end
end
