# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenwatch < Formula
  desc "Sync your Claude Code & Codex token stats to TokenWatch"
  homepage "https://tokens.onewheelgeek.net"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.1/tokenwatch_darwin_amd64.tar.gz"
      sha256 "7613e3f134b7e4245504e763b5e7d890e1f2411e0bf0d4f40b5c29241c19b3e8"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.1/tokenwatch_darwin_arm64.tar.gz"
      sha256 "9ddde6eea6401ce0addef5d3f4fe7853c2207d29dde3834410716e9c17942fd4"

      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.1/tokenwatch_linux_amd64.tar.gz"
      sha256 "9032c9f01602177a144ebc1f0ea2672556401f9be8b0376c0b109f436e836f90"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jclement/tokenwatch/releases/download/v0.3.1/tokenwatch_linux_arm64.tar.gz"
      sha256 "245e42379907d029e9a3532893f7a9bab1f461537c4250528d349b61d9e0ee28"
      define_method(:install) do
        bin.install "tokenwatch"
      end
    end
  end

  def caveats
    <<~EOS
      Pair this device with a code from https://tokens.onewheelgeek.net (Settings):
        tokenwatch --pair <CODE>
      Then sync once with `tokenwatch` or continuously with `tokenwatch --continuous`.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokenwatch --version")
  end
end
